# Enable all rules by default
include: ../analysis_options.yaml
linter:
  rules:
    # Not necessary for examples
    public_member_api_docs: false

    # Useful for packages but not for apps
    type_annotate_public_apis: false

    # Not necessary for examples
    use_key_in_widget_constructors: false
