# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 'Check Commit Message'

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commit messages
        id: commit_message
        run: |
          commits=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:"%s" | grep -vE '^Merge branch')
          echo "$commits"
          if echo "$commits" | grep -Eqv '^sp\d{2,}\sDPCAPP-\d+\s.*'; then
            echo "One or more commit messages do not match the required pattern."
            echo "$commits" | grep -Ev '^sp\d{2,}\sDPCAPP-\d+\s.*'
            exit 1
          fi
          

