# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 'tagged-release'

on:
  push:
    tags:
      - "v*"

jobs:
  android:
    name: 'build android apk'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore.jks'
          fileDir: './android/app/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}

      - run: flutter pub get

      - name: build bundle
        run: flutter build appbundle
        env:
          SIGNING_KEYSTORE_PATH: ./keystore/keystore.jks
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: build android app
        run: flutter build apk --split-per-abi
        env:
          SIGNING_KEYSTORE_PATH: ./keystore/keystore.jks
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          files: |
            build/app/outputs/flutter-apk/*
            build/app/outputs/bundle/release/app-release.aab
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: false
