# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 'tagged-release'

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: 'Tagged Release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/your_signing_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - run: flutter test

      - name: build
        run: flutter build apk --split-per-abi
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload to github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          files: "build/app/outputs/apk/release/*"
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: true
